### ISSUE TITLE
Lecture 12 Assignments, due Monday 6/3

### ISSUE THREAD

**Issue by JoelScarinius** [Civil-Data/Bomb-IT#121]
Add a software license to your project.  Decide if you would like to make the project public.

- [x] create an issue titled "Lecture 12 checklist" to track these checklist items
- [x] Project has a software license
- [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work.
- [x] [Optional] Present your project at the Lab session on 2 March. (something simple: 5 to 10 minutes)

**Comment by rudymatela** [comment]
The checklist items seem to be complete.  :-)  Good job!
