### ISSUE TITLE
Lecture 5 Assignments, due date Wednesday 1/2

### ISSUE THREAD

**Issue by JoelScarinius** [Civil-Data/Bomb-IT#30]
- [x] Continuous Integration (CI) through GitHub Actions.
- [x] CI checks that your code compiles or parses.
- [x] CI checks that the unit tests are passing. 
- [x] master/main is passing / green.
- [x] CI "badge" on the README
- [ ] CI produces code coverage information.
- [x] CI performs lint checks.

**Comment by rudymatela** [comment]
@MarrisSparrisNilsson, @Stocken99, @JoelScarinius, @McFluffen, @matildaronder and @Lukasydkvist,

### General Feedback

* Nice work getting your project building on GitHub Actions CI.  I know that for Unity projects this is not a trivial task, so good job figuring it out, discovering, using and configuring the `game-ci/unity-test-runner` plugin.  :+1:  :tada:
* FYI: you have 552 lines of C# code in the GameLogic and GameContent folders.   :slightly_smiling_face: 
* Nice that you solved the duplicate directory structure issue "Bomb-IT/Bomb-IT".  Now files reside in the repository root, so it's looking better than before.  :+1:
* Here's a general suggestion for improvement: you could add a screenshot to the README if you like.  :-)  Or [even an animated gif](https://github.com/rudymatela/tankode#readme).  (Not a requirement, just a suggestion if you like.)

### Checklist items

You seem to have completed all the mandatory checklist items for lecture 5.  :heavy_check_mark:   Good job!  :tada:

I unfortunately could not figure out how to find code coverage information for CI runs:

* [ ] CI produces code coverage information.

I checked both the [build logs](https://github.com/Civil-Data/Bomb-IT/actions/runs/4079398271/jobs/7030736815) and the [generated artifacts](https://github.com/Civil-Data/Bomb-IT/actions/runs/4079398271/jobs/7036842420) but couldn't find the code coverage percentage there.  Maybe I'm not looking in the right place?  :thinking: :thought_balloon:

Anyway, again, the mandatory items have been completed.  :tada:
