### ISSUE TITLE
Lecture 6 Assignments, due date Thursday 2/2

### ISSUE THREAD

**Issue by JoelScarinius** [Civil-Data/Bomb-IT#31]
- [x] Your project has pull requests and code review.
- [x] Each student has created at least one pull request.
- [x] Each student has performed at least one code review.
- [x] Each student has merged his own pull request after the code review.
- [x] master/main is passing / green. (and should be always from now on!)

**Comment by Stocken99** [comment]
Please see issue #69

**Comment by rudymatela** [comment]
The checklist for lecture 6 seems to be complete.  :tada:

(Detailed feedback on #30.)
