### ISSUE TITLE
Pull request and Code review : Checklist for 2/2 Tasks

### ISSUE THREAD

**Issue by Stocken99** [Civil-Data/Bomb-IT#69]
Checkboxes for keeping track of who have done a pull request and code review. 
==
## Pull Requests :

 - [x] Felix
 - [x] Joel
 - [x] Martin
 - [x] Matilda
 - [x] Jacob
 - [x] Lukas

## Code Reviews:

 - [x] Felix
 - [x] Joel
 - [x] Martin
 - [x] Matilda
 - [x] Jacob
 - [x] Lukas

##  Each student has merged his own pull request after the code review.

 - [x] Felix
 - [x] Joel
 - [x] Martin
 - [x] Matilda
 - [x] Jacob
 - [x] Lukas

**Comment by MarrisSparrisNilsson** [comment]
nice
