### ISSUE TITLE
Lecture 7 Assignments, due date Friday 10/2

### ISSUE THREAD

**Issue by JoelScarinius** [Civil-Data/Bomb-IT#78]
Carry on with your project implementation.  Make your first release v0.1.0 using [Semantic Versioning](https://semver.org/) by creating a git tag v0.1.0.

* [x] Make your first release v0.1.0 by creating and pushing a tag through git.
* [x] Generate [a build artifact](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts) through CI.  This can be anything that makes sense to your project: an executable file, a code coverage report, an installer for the built version, etc.
* [x] Carry on with your implementation adding more features to your project: use issues and PRs to track your work.
* [ ] (Optional) (if your project is a "desktop" project, you may choose to do this if you like) When a commit is tagged with a version (v0.1.2), a release artifact is generated: this may be a simple executable or an installer
* [ ] (Optional) (if your project is a "web" project, you may choose to do this if you like) When a commit is tagged with a version (v0.1.2), the application is deployed on a (testing) server

**Comment by rudymatela** [comment]
I have updated the checklist items for Lecture 7 now on Canvas.  I am replicating the changes here just so you are aware.  :grin:

**Comment by rudymatela** [comment]
@MarrisSparrisNilsson, @Stocken99, @JoelScarinius, @McFluffen, @matildaronder and @Lukasydkvist,

I see the release and the build artifact.  I was able to run the build artifact on Linux through [Wine](https://www.winehq.org/):

![options](https://user-images.githubusercontent.com/3999598/218708508-08cdca8b-cf6e-4c57-9405-eed64e6d10ac.png)

I am able to navigate to the options, change resolution and quit.

Good job with this.  :tada:

I see that you artifact was shipped with the `StandaloneWindows64_DoNotShip` folder.  I am not a specialist on Unity, but my guess is that this folder should not be shipped with the binary release.  :grin:  I managed to run the game after deleting it.  You can look into that if you like.

I see that you are tracking your work through PRs with code review.  Good job with this as well.  (Maybe you could have issues mirroring each of the PRs with the details of the interface and maybe ultimately with screenshots?  :thinking: :thought_balloon:)

In all, the checklist items for lecture 7 seem to be complete.  I am closing this issue.
