### ISSUE TITLE
Lecture 10 Assignments, due Monday 27/2

### ISSUE THREAD

**Issue by MarrisSparrisNilsson** [Civil-Data/Bomb-IT#98]
- [x] Create an issue titled "Lecture 10 checklist" to track these checklist items
- [ ] Each student has created at least two to five unit tests with matching PRs and code review **See comment down below**
- [x] Project has at least one of the following types of tests:
  * Integration tests
  * Nonfunctional tests (e.g.: performance, capacity)
  * Property tests
- [x] Code coverage of tests is increased by at least 20%.  List the "starting" and "ending" commits in the "Lecture 10 checklist" issue with the achieved percentage increase.
- [x] `main` is still passing / green. (and should be always from now on!)

**Comment by Stocken99** [comment]
Pull request for testing of movement and mapgeneration : #55

**Comment by Stocken99** [comment]
#102 Pull Requests for testing the change to godMode in the GetALife method, Also a KillPlayerTest

**Comment by Stocken99** [comment]
###Each student has created at least two to five unit tests with matching PRs and code review

- [ ] Martin
- [ ] Matilda
- [ ] Joek
- [ ] Lukas
- [ ] Felix
- [ ] Jacob

**Comment by JoelScarinius** [comment]
Created more unit tests to map generator and separated tests into to different files in PR #108

**Comment by rudymatela** [comment]
> Starting commit for code coverage: Pull request for testing of movement and mapgeneration : #55
> 
> ![Image](https://user-images.githubusercontent.com/103746883/221614725-ffa8b511-cda6-42af-8450-2db1d0d7c2e2.png)
> 
> ![Image](https://user-images.githubusercontent.com/103746883/221614833-b94267d8-3521-4dd1-83b9-cfb0fe1750e8.png)
> 
> Ending commits for code coverage : Pull request for our final code coverage review : #112 Total Change of code coverage is over 100%. This is because we have added covered projects in unity. Which decrease the total percentage. However the amount of lines is more than doubled!
> 
> ![Image](https://user-images.githubusercontent.com/103746883/221614963-907c47c8-3693-4fc4-ad52-28d4e8197496.png)
> 
> ![Image](https://user-images.githubusercontent.com/103746883/221615040-691802fb-952b-41d5-b977-cceb5f80ee30.png)
> 
> In conclusion we have increased coverable lines of code to 523 from 124 and we now cover 317 lines of code instead of 124 so we have increased our codecoverage beacause before we didn't include all our code in our code coverage reports.

Fair enough.  :slightly_smiling_face:   Thanks for the detailed explanation and for gathering the data.  :grin:

**Comment by rudymatela** [comment]
@MarrisSparrisNilsson, @Stocken99, @JoelScarinius, @McFluffen, @matildaronder and @Lukasydkvist,
The checklist items seem to be complete.  Good job!  :tada:
